require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/DescribeClass:
  Exclude:
    - spec/system/**/*.rb

RSpec/DescribeMethod:
  Exclude:
    - spec/requests/**/*.rb

RSpec/FilePath:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false
